In [ ]:
import numpy as np

1.Create a numpy of integers from 1 to 10

In [ ]:
arr= np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2.2X3 numpy array with filled with Zeros

In [ ]:
arr2=np.zeros([2,3])

In [ ]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

3.Create a NumPy array of even numbers from 2 to 20.

In [ ]:
arr3=np.arange(2,22,2)

In [ ]:
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4.Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]), perform element-wise addition, subtraction, multiplication, and division between the two arrays

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr1

array([1, 2, 3])

In [ ]:
arr2=np.array([4,5,6])

In [ ]:
arr2

array([4, 5, 6])

In [ ]:
#Addition
arr3=arr1+arr2

In [ ]:
arr3

array([5, 7, 9])

In [ ]:
#subsraction
arr4=arr1-arr2

In [ ]:
arr4

array([-3, -3, -3])

In [ ]:
#Multiplication
arr5=arr1*arr2

In [ ]:
arr5

array([ 4, 10, 18])

In [ ]:
#division
arr6=arr1/arr2

In [ ]:
arr6

array([0.25, 0.4 , 0.5 ])

5.Compute the mean, median, and standard deviation of a NumPy array containing 100 random numbers


In [ ]:
arr7=np.random.rand(100)

In [ ]:
arr7

array([0.85012136, 0.57860222, 0.28648839, 0.9736234 , 0.92832384,
       0.1815361 , 0.83964707, 0.48789374, 0.21886964, 0.34075555,
       0.03183848, 0.75863186, 0.71512814, 0.01986087, 0.27604532,
       0.51535586, 0.58519679, 0.7125589 , 0.46357945, 0.3622077 ,
       0.48812057, 0.59463473, 0.49833619, 0.53202803, 0.16641982,
       0.55932826, 0.36024041, 0.33614618, 0.14042271, 0.13463651,
       0.27117135, 0.27645539, 0.62519102, 0.17796315, 0.47091838,
       0.41332121, 0.23683143, 0.27757387, 0.74329909, 0.59597102,
       0.50616485, 0.70078018, 0.72494997, 0.04670442, 0.02433931,
       0.94796017, 0.79572309, 0.72132233, 0.75300082, 0.3962217 ,
       0.10706805, 0.25160583, 0.01661161, 0.20926424, 0.72495732,
       0.20392927, 0.84740133, 0.66998089, 0.86970173, 0.72305492,
       0.44447399, 0.1598369 , 0.47820524, 0.46345338, 0.44268895,
       0.82433523, 0.99577695, 0.49298376, 0.3888026 , 0.46327895,
       0.85913126, 0.11990269, 0.54716995, 0.66088171, 0.05985

In [ ]:
#mean
arr7.mean()

0.48810973964097465

In [ ]:
#standard deviation
arr7.std()

0.2645252277244683

In [ ]:
#median
median=np.median(arr7)

In [ ]:
median

0.4880071503702331

6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).


In [ ]:
arr8=np.random.randint(0,20,12)

In [ ]:
arr8

array([13, 10, 15, 10, 18, 11,  5,  8,  2, 10, 14,  4])

In [ ]:
arr8.reshape(3,4)

array([[13, 10, 15, 10],
       [18, 11,  5,  8],
       [ 2, 10, 14,  4]])

7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions.


In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

8. Create a 5x5 identity matrix using NumPy

In [ ]:
arr9=np.eye(5,5)

In [ ]:
arr9

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6]).

In [ ]:
a=np.array([1,2,3])

In [ ]:
b=np.array([4,5,6])

In [ ]:
a.dot(b)

32

10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.

In [ ]:
arr10=np.arange(0,21)

In [ ]:
arr10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
arr10.max()

20

In [ ]:
arr10.min()

0

11.Concatenate two random NumPy arrays horizontally and vertically.

In [ ]:
arr1=np.zeros((3,3))

In [ ]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr2=np.ones((3,3))

In [ ]:
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.vstack([arr1,arr2])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.hstack([arr1,arr2])

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

12.Given a 2D NumPy array, calculate the sum of each row and each column
separately

In [ ]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print("the sum of each coloum",np.sum(arr,axis=0))
print("the sum of each row",np.sum(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
the sum of each coloum [28 32 36 40]
the sum of each row [10 26 42 58]


13.Find the common elements between two NumPy arrays

In [ ]:
a=np.array([[2,3],[4,5],[6,7]])
b=np.array([[1,3],[3,5],[4,8]])
c=np.intersect1d(a,b)
print("the common elements of a and b are",c)


the common elements of a and b are [3 4 5]


14.Replace all negative values in a NumPy array with zeros

In [ ]:
a=np.array([1,2,3,-4,-5,-6])
a[a<0]=0
a

array([1, 2, 3, 0, 0, 0])

15.Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order.


In [ ]:
arr=np.random.randint(1,101,100)

In [ ]:
arr

array([  5,  75,  84,  32,  99,   3,  90,  15,  59,  77,  26,  54,  43,
        15,  38,  92,  57,  82,  66,  97,  53,  51,  45,  59,  22,  47,
        21,   8,  59,  40,  85,  58,  89,  63,  65,  55,  11,  60,  45,
        67,  18,  53,  45,  12,   4,  16,  53,  59,   1, 100,  18,  44,
        15,  73,  38,  55,  73,  30,  92,  75,   8,  85,  82,  11,  30,
        57,  30,  14,  93, 100,   3,  97,  78,  22,   9,  90,   5,   8,
         6,  89,  22,  25,  14,  83,  46,  48,  45,  26,   7,  54,   7,
        22,  74,  35,  51,  55,  21,  65,   2,  94])

16.Calculate the element-wise absolute difference between two NumPy
arrays.

In [185]:
a=np.array([1,2,3,4,5])
b=np.array([8,10,12,14,16])
c=np.absolute(a-b)
print("the element-wise diff b/w the two array is",c)

the element-wise diff b/w the two array is [ 7  8  9 10 11]


17.Given a 2D NumPy array, extract the first row and the last column

In [186]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
firstrow=arr[0]
lastcol=arr[:,[-1]]
print('first row is\n',firstrow)
print("last column is\n",lastcol)

first row is
 [1 2 3]
last column is
 [[3]
 [6]
 [9]]


18.Slice a 1D NumPy array to get every other element.

In [188]:
a=np.array([1,2,3,4,5])
x=a[0:len(a)+1]
print(x)

[1 2 3 4 5]


19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements.

In [189]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[11,13,14,15,16,17],[11,22,33,44,55,66],[23,23,34,56,32,12],[1,22,33,23,22,55]])
x=arr[2:4,[2,3]]
print("orginal array is",arr)
print("central 2x2 element",x)

orginal array is [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [11 13 14 15 16 17]
 [11 22 33 44 55 66]
 [23 23 34 56 32 12]
 [ 1 22 33 23 22 55]]
central 2x2 element [[14 15]
 [33 44]]


20.Reverse a 1D NumPy array using slicing

In [190]:
a=np.array([1,2,3,4,5])
x=a[::-1]
x

array([5, 4, 3, 2, 1])